name: Release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Toolchain
      id: toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: "wasm32-unknown-unknown"
        components: "clippy, rustfmt"
    - name: Wasm
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          target/
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-rustc-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('Cargo.toml', '.github/workflows/deploy.yml') }}
    - name: Compile
      run: ./scripts/build
    - name: Package
      run: tar -czvf star_trip-${{ github.ref_name }}.tar.gz www
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: star_trip-${{ github.ref_name }}.tar.gz
          draft: true
